name: kube-score

on:
  push:
    branches:
      - main

jobs:
  kube-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Run kube-score using official Docker image
        run: |
          helm template . | docker run --rm -i zegl/kube-score:latest score -
