name: kube-score

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  kube-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Run kube-score on all local charts
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "🔍 Running kube-score for $chart..."
              helm template "$(basename "$chart")" "$chart" | \
              docker run --rm -i zegl/kube-score:latest score - || exit 1
            fi
          done
